// Created by iWeb 2.0.4 local-build-20100327

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'About_files/stroke_1.png'},{rect:new IWRect(2,-2,96,4),url:'About_files/stroke_2.png'},{rect:new IWRect(98,-2,4,4),url:'About_files/stroke_3.png'},{rect:new IWRect(98,2,4,96),url:'About_files/stroke_4.png'},{rect:new IWRect(98,98,4,4),url:'About_files/stroke_5.png'},{rect:new IWRect(2,98,96,4),url:'About_files/stroke_6.png'},{rect:new IWRect(-2,98,4,4),url:'About_files/stroke_7.png'}],new IWSize(100,100)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'About_files/stroke_9.png'},{rect:new IWRect(2,-2,96,4),url:'About_files/stroke_10.png'},{rect:new IWRect(98,-2,4,4),url:'About_files/stroke_11.png'},{rect:new IWRect(98,2,4,96),url:'About_files/stroke_12.png'},{rect:new IWRect(98,98,4,4),url:'About_files/stroke_13.png'},{rect:new IWRect(2,98,96,4),url:'About_files/stroke_14.png'},{rect:new IWRect(-2,98,4,4),url:'About_files/stroke_15.png'}],new IWSize(100,100)),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_files/stroke_24.png'},{rect:new IWRect(-2,-2,4,4),url:'About_files/stroke_25.png'},{rect:new IWRect(2,-2,96,4),url:'About_files/stroke_26.png'},{rect:new IWRect(98,-2,4,4),url:'About_files/stroke_27.png'},{rect:new IWRect(98,2,4,96),url:'About_files/stroke_28.png'},{rect:new IWRect(98,98,4,4),url:'About_files/stroke_29.png'},{rect:new IWRect(2,98,96,4),url:'About_files/stroke_30.png'},{rect:new IWRect(-2,98,4,4),url:'About_files/stroke_31.png'}],new IWSize(100,100)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'About_files/stroke_17.png'},{rect:new IWRect(2,-2,96,4),url:'About_files/stroke_18.png'},{rect:new IWRect(98,-2,4,4),url:'About_files/stroke_19.png'},{rect:new IWRect(98,2,4,96),url:'About_files/stroke_20.png'},{rect:new IWRect(98,98,4,4),url:'About_files/stroke_21.png'},{rect:new IWRect(2,98,96,4),url:'About_files/stroke_22.png'},{rect:new IWRect(-2,98,4,4),url:'About_files/stroke_23.png'}],new IWSize(100,100)),reflection_0:new IWReflection({opacity:0.50,offset:1.00})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_files/AboutMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
